### ISSUE TITLE
Sidebar Outline styles no longer valid

### ISSUE THREAD

**Issue by lastobelus** [Dmitriy-Shulha/obsidian-css-snippets#11]
The names of the styles in the sidebar outline have changed.

Here is the css I use, with a screenshot of it in action. It adds indenting of headings that wrap, uses a lighter weight font for leaf items, and uses `rem` units so that it zooms in/out cleanly.
I also use override variables as I do in most of my snippets. The default variable is one available in the app variables, and the override one is specific to the snippet so that the snippet can easily be customized per-theme.

```css
.outline {
  font-size: 0.8rem;
  font-weight: 200;
}

.outline .tree-item {
  line-height: 1.3;
}

.outline .tree-item-self {
  padding-top: 0.2rem;
  padding-bottom: 0.1rem;
  padding-left: 0.5rem;
  padding-right: 0.3rem;
}  

.outline .tree-item-collapse {
  left: 0.1rem;
}  

.outline .tree-item-inner{
  position:relative;
  padding-top: 0.2rem;
  /* padding-left: 1rem; */
  padding-left: 1.7em;
  text-indent: -0.8em;
  margin-left: 0.2rem;
  /* font-size: 0.9em; */
}  

.outline .tree-item-children {
  margin-left: 0.7rem;
  padding-left: 0.5rem;
  margin-top: -0.3rem;
  padding-top: 0.3rem;
  border-left: 1px solid var(--sidebar-marks, var(--background-modifier-border));
  border-radius: 4px;
  transition:all 0.5s ease-in-out;
}

.outline .tree-item-children:hover {
  border-left-color: var(--sidebar-marks-hover, var(--background-secondary));
}

.outline .collapse-icon + .tree-item-inner {
  font-weight: 400;
  padding-left: 0.2rem;
  /* margin-left: 0rem; */
  /* font-size: 1em; */
}

.outline .collapse-icon {
  margin-top: 0.2rem;
  margin-left: -0.4rem;
  margin-right: -0.4rem;
  width: 2rem;
}
```

<img width="123" alt="screenshot-of-sidebar-outline-tweaks-hover" src="https://www.evernote.com/l/ARafkrqC4gBDV7RFfcsIP8cU_J2c6vksRecB/image.png">
